### PR TITLE
Faux123 v001 aosp ics - adds AOSP USB and fixes omx for camcorder

### PR DESCRIPTION
**Pull request by Albinoman887**
sorry i know it should really only be 3 commits i messed up the order somehow but this PR is kinda important as it fixes the camcorder

### CODE REVIEW

**Comment by faux123** [comment]
I have reverted the move of KGSL folders.  I understand the motivation for doing so, but I am not ready to do so myself.  Maybe somewhere down the line I will follow this approach but not yet for the first few versions.

**Comment by Albinoman887** [comment]
ok so should i re fork your repo? how to i become inline with it again?

**Comment by Albinoman887** [comment]
never mind figured it out

**Comment by showp1984** [comment]
btw you might want to add these 2 commits on top of it:
https://github.com/showp1984/bricked-pyramid-3.0/commit/d8726484c1612eb1e49725d47ce3d1bf81bfd80d
https://github.com/showp1984/bricked-pyramid-3.0/commit/93e0593ab0b5627947abc3b00ebc6b064542767d

2 epic array boundary fails.

**Comment by Albinoman887** [comment]
Alright will test it out, this is a pretty safe merge correct as in it
shouldn't break anything
On Mar 25, 2012 1:06 PM, "show-p1984" <
reply@reply.github.com>
wrote:

**Pull request merged**
